sudo: required
services: 
  - docker

# build react production version
before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

# primary test running section
# you run the image with a command npm test.
# -- --coverage is to exit the test after running the test
script:
  - docker run react-test npm test -- --coverage

# no need to specify dockerfile because Dockerfile is the default.
after_success:
  - docker build -t react-client ./client
  - docker build -t react-nginx ./nginx
  - docker build -t react-server ./server
  - docker build -t react-worker ./worker