sudo: required
language: generic 
services: 
  - docker

# build react production version
before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

# primary test running section
# you run the image with a command npm test.
# -- --coverage is to exit the test after running the test
script:
  - docker run -e CI=true react-test npm test -- --coverage

# no need to specify dockerfile because Dockerfile is the default.
after_success:
  - docker build -t shaun210/react-client ./client
  - docker build -t shaun210/react-nginx ./nginx
  - docker build -t shaun210/react-server ./server
  - docker build -t shaun210/react-worker ./worker

  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push the images to docker hub
  - docker push shaun210/react-client
  - docker push shaun210/react-nginx
  - docker push shaun210/react-server
  - docker push shaun210/react-worker

# incredible